# Generated by Django 6.1.1 on 2026-09-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], max_length=20)),
                ('release_year', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('duration', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=150)),
                ('cast', models.TextField()),
                ('poster_url', models.URLField()),
                ('banner_url', models.URLField()),
                ('trailer_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
